version: '3.1'

services:
  mysql:
    image: arm64v8/mysql
    container_name: mysql-server
    restart: always
    environment:
      - MYSQL_DATABASE=birthday_for_friends
      - MYSQL_ROOT_PASSWORD=toor
    ports:
      - 3306:3306
  adminer:
    image: adminer
    container_name: adminer-server
    restart: always
    environment:
      - ADMINER_DEFAULT_SERVER=mysql-server
    ports:
      - 9000:8080
